services:
  - type: web
    name: codeai
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: GOOGLE_API_KEY
        value: your-api-key
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
